import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import 'tables/content_tables.dart';

part 'app_database.g.dart'; // generated by build_runner — see README

@DriftDatabase(tables: [
  ContentItems,
  ContentSections,
  ContentFacts,
  TimelineEntriesTable,
  Flashcards,
  Mcqs,
  TopicProgress,
  ExamAttempts,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 2;

  // Migration strategy note (spec section 21/31): when a new PDF is
  // ingested we only ever INSERT/UPDATE rows via the repositories —
  // we do not bump schemaVersion unless the *shape* of the data changes.
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
        },
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            // Adds TopicProgress.isRead — feeds the "পড়া হয়েছে" badge on
            // the Study screen (didn't exist in the very first schema).
            await m.addColumn(topicProgress, topicProgress.isRead);
          }
        },
      );
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'bangla_sahitya.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
